"""Modificamos el modelo para mejor comprensión, agregando las nuevas relaciones y columnas en las tablas correspondientes.

Revision ID: d81052b5bef3
Revises: d4a6fe810f14
Create Date: 2024-09-16 15:35:58.910470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd81052b5bef3'
down_revision: Union[str, None] = 'd4a6fe810f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Tabla 'cost_production': 
    # - Se añade la columna 'total_cost' 
    # - Se eliminan columnas obsoletas 'cant_materia_prima' y 'product_material_id'
    # - Se elimina la clave foránea asociada a 'product_material_id'
    # - Se crea un índice para 'cost_production_id' (si no existe)
    op.add_column('cost_production', sa.Column('total_cost', sa.Float(), nullable=False))
    op.drop_constraint('cost_production_product_material_id_fkey', 'cost_production', type_='foreignkey')
    op.drop_column('cost_production', 'cant_materia_prima')
    op.drop_column('cost_production', 'product_material_id')
    # Nota: El índice 'ix_cost_production_cost_production_id' se crea solo si no existe. 
    # Si ya existe, esta línea no tendrá efecto y evitará errores.
    op.create_index(op.f('ix_cost_production_cost_production_id'), 'cost_production', ['cost_production_id'], unique=False)

    # Tabla 'product_material':
    # - Se añade la columna 'quantity_used'
    # - Se eliminan y recrean las claves foráneas con 'products' y 'stock_materia_prima' para asegurar consistencia
    # - Se crea un índice para 'id' (si no existe)
    op.add_column('product_material', sa.Column('quantity_used', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_constraint('product_material_stock_materia_prima_id_fkey', 'product_material', type_='foreignkey')
    op.drop_constraint('product_material_products_id_fkey', 'product_material', type_='foreignkey')
    op.create_foreign_key(None, 'product_material', 'stock_materia_prima', ['stock_materia_prima_id'], ['stock_materia_prima_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_material', 'products', ['products_id'], ['products_id'], ondelete='CASCADE')